---
- name: Reconfigure HTCondor
  ansible.builtin.command: condor_reconfig
  changed_when: true

- name: Restart HTCondor
  ansible.builtin.systemd:
    name: condor
    state: restarted

- name: Reload systemd units
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart docker
  ansible.builtin.systemd:
    name: docker
    state: restarted
